### ISSUE TITLE
in readme usage.md is missing

### ISSUE THREAD

**Issue by Nic30** [ben-marshall/microcoder#2]

**Comment by Nic30** [comment]
(main readme...)

**Comment by ben-marshall** [comment]
Sorry, I don't understand. `docs/usage.md` is missing from the main `README.md`?

**Comment by Nic30** [comment]
on main page https://github.com/ben-marshall/microcoder If I click on "here"
> More information on what this tool might be used for is found "here".

there is 404:
https://github.com/ben-marshall/microcoder/blob/master/usage.md

**Comment by Nic30** [comment]
(because path is incorrect)

**Comment by ben-marshall** [comment]
Ah! I see, cheers :+1:
